server:
  port: 8085
spring:
  config:
    activate:
      on-profile: prod
  application:
    name: pili-service
  datasource:
    url: jdbc:mysql://123.57.139.0:3306/bili?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Lz001126.
    driver-class-name: com.mysql.cj.jdbc.Driver

ip: http://49.235.146.19:8082
resource:
  prefix: /project/
  path:
    video: /pili/data/resource/
    avatar: /pili/data/avatar/
    sys: /pili/data/sys/
    mg: /pili/data/mg/
    animation: /pili/data/animation/

alipay:
  appId: 9021000141641323
  appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCqfKT/6cZ9V85tneItF93KRV+JGXkQlOQzP09ekDN+gaNWm6XFFmbYtqqhPmcIC7dPN9AfqoaEWeZua4xPyQX8xvsHvjNEsUh9BbQWQzZdKAZm69AX08mJq31jiF+oD5r57n+Hbdd9g4Lg7b3vdnDjY7zkJyUpCgRCSk2YzG/EFPdMwvkEGyVFN1Oq+69r/KmCdzKxwvGTupRId+Gre3PhAd+kxygWq48MF4sczVbclCN0Q5Pm2KLDk6zyz9z8r2NKEa09IAH0sWspzO8c6LKmSSF4nRjbGfUQgXrfrH2mkzvYRlNZszkP+nm/MOSFZLPqLYulKSH94GHhoIGRTzdTAgMBAAECggEBAJueDMpf7ENLW+zo2aQJjfRs4Gh3bO96yNYSavNJMwe9c4fBqU2+RgB4tEVcfZV1hEx2CK5u7DxxBwoxdzD4sFNsmYUW0xtXq3AbPae4kC32M+nMQ/UL54GXnGu29oGkRPTwA05uL+2sllGUEPQ8q4yT5L5pEN1l/D86LZxUt4xFid9MQr3g7HlxOSitvLGTq3/F47HzJmgdL0YJDa+908Qj3nIi4bW0OdBYPWe9aJcx2uMZL0YV79ackhnAYjrVCHn3iGFcfH/O/zuMVyAefLt/bPmkamRWjhtiY0yOLBNMMqF1nmFsG4SQ+G0abWIKWwQInAM7tpJparjvAkGROOECgYEA8C7iaTd500CtKqsRNe32+EaYpuQeNs38pPq/85wP8xYpggZAxujHeNKchm4NKVVFdydVBgypHk6MHNcR6HN0v+ZLcy7Hgm1JKi8jNZmRlHIgzVi4ztGB3kEFraeBdmnsjpicyHJnIf9eF3TyV9PUZ5YZ3rAGXwCJdjJufWIx9MMCgYEAtbbKErguIAUAzyUTHnnW9NASsGJz8C/rs6A93mt2zYtNKoKLabJ1pBbvzQL1OWsjX5ZsGSe+w2JFYoXABJq5/ix0PFH/9Q/0CpXQ0HzDtHjKWI/jG6Hh2yfKuFPUDORvBMx+Oys+ddn5J05nkfWnpGkMNTLCxClhFW7Z2KsVSjECgYEAv8F+y+gZoFqbplwrgnX5XmDmkR/BK5orYgA77h+j8Dy6aO/bGbNRRhpIE1+brGtC6Y2CaTEEeIjXflMLHh3HkUoo5M3tRSlBZ6d4odt4ih7QJ4H1ElHcMHiTMwBv8P1CetpHGhWUV2VNVsbskMgzZXxGLS819vUzyiUbZ4lVPwcCgYBFDzoPETZebuhW0WVJwM5j7iwcIt6jGuM+OhkpTbgx984U6NYpDmzNNvZd+NDPyJsB+f4NNWC3isKJ5gEK/u7O3YAzaIqZTT3XRAa/JZuPHBTywYRzfPuEOcQ+d4VwfOSAc2NKA25Shcu+F3sfKrhSsKW2FhuVR5Cg/6cFREfsEQKBgESXfE9+7coeKOTFmYsViPcdoLoMPLYA4ztMde0dwgE4vWJ50zrMCvVHwP0rOX0dQ65E5JcMwueSkvnaWUIFQaDdBDYGbR1ZEAFI9No3vbJCLtJNN8hYjuLZOlOJ1JaqUlPK8mpZZQLE4uscff4EEn3DCKWxumUikG8FDd8KH6uW
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAi7pphF/FmsoZiMF70yQqXTyyoxrtNGKCfkm4YK1p20h9Qy3fJwqGe0sJ0ZAEZRJ5/rN7BR+t88vMnJWmVOce07WEAmoYW/Yu9J7MkhX0P3q/lMDoV9koMfsiGhP5QT0ut+yO74M1XPgQabNGZChxFQtoP5dMxuxnA2UprjY45YoXh6TEzLjk0CgBqDUNJjIiJfI7yb8UoLh1o5sGNhdHWrz/7njJivwnNIuHlbQcPhQcJqBRjUGrbAob6UGiQP3rUU0dh0yPL6LwAz7Fq+ifd6ggsqharbJlxrr5ovsjwfrW7cvBbF2S+1RbI52zFDBIkKn8NhayhCwEEXh8npuUEwIDAQAB
  # （回调接口）
  notifyUrl: http://437c2a12.r12.cpolar.top/alipay/notify